package dam.projects.projectdam;

/**
 * Created by renat on 07/04/2016 : 19:51.
 */
public class InfoClass {
    // just to keep the project's package from being auto-deleted
    // by githuh

    // create new packages inside dam.projects.projectdam
    // to keep our code organized by modules

    // package name examples:
    // -interface - for graphical user interface
    // -network - internet connections
    // -mysqlite - database related classes
    // -utility - miscellaneous classes
    // -helpers - classes with helpful methods to use everywhere
    // -api - API related classes

    // set your file header to:
    // /**
    //   * Created by ${USER} on ${DATE} : ${TIME}.
    //   */
    // GO TO->file->settings->editor->code style->file and code templates->includes->file header

    // YOUR .gitignore file should look like this (protects your proxy password if you have one):
    //  *.iml
    //  .gradle
    //  /local.properties
    //  /gradle.properties
    //  /.idea/workspace.xml
    //  /.idea/libraries
    //  .DS_Store
    //  /build
    //  /captures

    // every method that is created / altered should have a quick resume / comment like this:
    /**
     * Method does things [OPTIONAL]
     * By Renato (name example)
     * Last change: 2016-05-06 (date example)
     * Resume of what was changed inside the method
     * @param example [OPTIONAL]
     * @return examples [OPTIONAL]
     */
    // NOTE: do not comment methods that are auto-generated by Android Studio, only if you
    // change / add something inside that wasn't previously auto-generated.

    // about commits and pushes to the remote repository, we must follow one convention!
    // #1 - The first paragraph represents the title of the commit. It should be short and
    //      and objective.
    //      5 keywords that should be ALWAYS applied FIRST:
    //          -Added
    //          -Altered
    //          -Improved
    //          -Fixed
    //          -Removed
    // #2 - The second (and beyond) paragraph are used to show more detailed information about
    //      the commit.
    //
    // Examples:
    // 1P-Added: Interface Activities
    // 2P-MenuActivity, (all activities you added)
    //
    // 1P-Fixed: Database connection error
    // 2P-Database class now allows JSON into the application without modifying database connection
    //
    // NOTE: 1P / 2P stands for First Paragraph / Second Paragraph

    // enough talking / writing! START WORKING!
    // @!EVERYTHING MUST BE WRITTEN IN ENGLISH!@ (except string.xml portuguese version)
    // do not commit and push bugs! (that's a big plus) :D

    // Renato Sá :D
}
